[package]
name = "promisc"
version = "0.0.1-alpha.1"
authors = ["nolash <dev@holbrook.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
